NUMPY GİRİŞ

In [1]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
a*b

array([ 2,  6, 12, 20])

In [2]:
?numpy

Object `numpy` not found.


In [3]:
x=9


In [4]:
x

9

In [5]:
L=[1,2,1.2,"a"]
[type(i) for i in L]

[int, int, float, str]

NUMPY2

In [7]:
import numpy as np 
a=np.array([1,2,3,4])
type(a)

numpy.ndarray

In [8]:
np.array([1,2,3,4],dtype="float32")

array([1., 2., 3., 4.], dtype=float32)

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.full((2,6),9)

array([[9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9]])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.linspace(0,1,30)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [15]:
np.random.normal(0,1,(3,4))

array([[-0.11725346,  0.41936843, -1.55659288, -0.61881563],
       [ 0.58818327,  0.86179751,  1.16990672,  0.77273224],
       [-0.1868474 ,  0.22739097, -2.30233769,  0.63104882]])

In [16]:
np.random.randint(0,10,(2,2))

array([[1, 0],
       [2, 3]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

biçimlendrme

In [1]:
import numpy as np

In [2]:
a=np.random.randint(10,size=(10,5))

In [3]:
a

array([[1, 9, 4, 1, 1],
       [0, 3, 5, 6, 7],
       [0, 2, 4, 0, 5],
       [4, 9, 7, 9, 8],
       [0, 0, 6, 5, 6],
       [3, 7, 1, 5, 7],
       [7, 1, 4, 4, 9],
       [5, 6, 0, 1, 6],
       [1, 5, 4, 3, 0],
       [4, 3, 3, 8, 8]])

In [4]:
a.ndim

2

In [5]:
a.shape

(10, 5)

In [6]:
a.size

50

In [7]:
a.dtype

dtype('int32')

In [8]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a=np.array([1,2,3])

In [15]:
a

array([1, 2, 3])

In [18]:
a.reshape(3,1)

array([[1],
       [2],
       [3]])

In [19]:
x=np.array([1,2,3])
y=np.array([4,5,6])


In [22]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])